### ISSUE TITLE
Style contact us  page

### ISSUE THREAD

**Issue by shreyait** [Google-Developer-Student-Club-CCOEW/Web-Development#3]

**Comment by lalelulelo** [comment]
Hi, is the issue still open ?

**Comment by sayli2003** [comment]
Please assign me this issue

I can make a simple yet stylish page to go along with the theme

**Comment by OjaswiPande** [comment]
OJASWI PANDE
SY COMP
CCOEW 
can you assign me this issue?

**Comment by ManasiGDeshmukh** [comment]
Manasi Deshmukh
CCOEW
SY Computer Department
I would like to work on this issue
can you assign this issue to me?

**Comment by drashan14** [comment]
Darshan Rathod
PCCOER
TY Computer Department
I would like to work on this issue
can you assign this issue to me?

**Comment by ManasiGDeshmukh** [comment]
Name : Manasi Deshmukh
CCOEW
Branch : Computer Engineering
I would like to work on this issue.
Can you please assign me this issue ?
